package lists

var MaleNames = []string {
"Sammy Five Fingers",
"Brayton Black Eyes",
"Collin the Silent",
"Calvert Angel Eyes",
"Ward the Con",
"Razor Forbes",
"Razortooth Newlin",
"Crazy Eyes Gerald",
"Slithering Welford",
"Diamond Antony",
"Leland the Phantom",
"Aaron the Robber",
"Sandford the Razor",
"Toby the Fang",
"Beaman Eyepatch",
"Knuckles Ansley",
"Mad Dog Barry",
"Razor Colborn",
"Crazy Eyes Elliot",
"Prowling Bennet",
"bhurn",
"skik",
"ern",
"glagssat",
"bhauthneir",
"stendret",
"prornvom",
"brurdam",
"dunbedbukr",
"orkusnik",
"van",
"thell",
"sum",
"garteik",
"fonled",
"kazgull",
"sotheis",
"aznalf",
"restraeddgand",
"jorvilskaul",
"redgris",
"barcig",
"gorgrath",
"grargox",
"gecnes",
"griozkag",
"murphobigg",
"hadralogg",
"sronirduk",
"brirardrad",
"halkaeth",
"ocdrak",
"drenshoz",
"strerath",
"sralaig",
"nirthigg",
"zesgiuziuc",
"kesijex",
"volerguk",
"honorca",
"Reisgric Berylbasher",
"Grulock Grumblebender",
"Kommer Jaderiver",
"Thisatin Pebbleforge",
"Noradgrit Copperrock",
"Strotmath Windguard",
"Kilmas Sapphirefall",
"Glorirgaed Boulderbuckle",
"Throznad Heavybelly",
"Hastreat Opalhelm",
"Yazzerlun Hammerbelly",
"Darmouck Chainmane",
"Gikhirlun Grumbleriver",
"Burgreag Cavepike",
"Tutrig Honorminer",
"Krafaed Frostcoat",
"Hossas Beastbrew",
"Buzmaeth Barrelback",
"Nerhear Heavymaker",
"Hokol Platebuster",
"Ralnor Nerifaren",
"Arathorn Olabalar",
"Ayluin Inara",
"Oslarelar Waeszana",
"Cailu Ravamaris",
"Kelvhan Helebalar",
"Aien Norbella",
"Belanor Morzorwyn",
"Ayred Enmaer",
"Ailmon Bijeon",
"Selanlar Sarrora",
"Iliphar Venlana",
"Kindroth Yeskrana",
"Ualair Bryna",
"Xhalh Tralynn",
"Reptar Keylana",
"Pharom Eldi",
"Onas Beinorin",
"Ailas Torthyra",
"Morthil Inajyre",
"ebfur",
"wathos",
"tunir",
"zeldor",
"wrirdius",
"hubar",
"krorvog",
"tubwor",
"fracnas",
"rurkos",
"kludsar",
"riam",
"nerkaros",
"sriznas",
"zofbos",
"iszus",
"axsar",
"nidus",
"iwbor",
"dlufius",
"mich",
"troabangug",
"crogoavosh",
"khondrurk",
"gon",
"ton",
"bogirs",
"taakda",
"gnalkros",
"torgaben",
"brach",
"siraarg",
"kreth",
"lodi",
"thrustaim",
"irverm",
"bredzigad",
"tesdath",
"tustril",
"gredaltroch",
"Holfast Hedgehopper",
"Adalbert Galpsi",
"Gorhendad Barrowes",
"Fredegar Silentfoot",
"Hunald Farfoot",
"Reginar Bottomhill",
"Theudebert Longfoot",
"Rigunth Galbassi",
"Adelard Lothran",
"Hartnid Noakesburrow",
"Conrad Brownlock",
"Alberic Goldworthy",
"Angilbart Baggins",
"Dodo Bracegirdle",
"Theuderic Took-Took",
"Gundahar Stumbletoe",
"Amalricus Sandheaver",
"Tim Greenhand",
"Doderic Hogpen",
"Deagol Noakes",
"bhalk",
"jorc",
"krok",
"fran",
"ghah",
"nezzarc",
"dhaaviah",
"rezgerk",
"gerzag",
"gradvid",
"Barkley Dyster",
"Albus Abbot",
"Carlton Bowman",
"Edwin Trinder",
"Kingsley Singer",
"Wilfred Lander",
"Edmund Hammer",
"Darcy Salter",
"Ramsey Warner",
"Lucious Lander",
}